name: Build

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"

env:
  GO_VERSION: 1.19

jobs:
  unit-tests:
    name: Unit Tests
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: ${{ env.GO_VERSION }}
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: 1.50.0
